### ISSUE TITLE
ct: api error 201: parameter, ct, is not modifiable

### ISSUE THREAD

**Issue by JanLp** [ebaauw/homebridge-deconz#113]
https://github.com/dresden-elektronik/deconz-rest-plugin/releases/tag/v2.20.1

homebridge-deconz v0.1.5-0

`[deCONZ] ZigbeeGW: warning: request 15597: /lights/3/state/ct: api error 201: parameter, ct, is not modifiable. Device is set to off.`

```
"CC86ECFFFE67D129": {
    "expose": true,
    "manufacturer": "IKEA of Sweden",
    "model": "TRADFRIbulbE14WSglobeopal470lm",
    "name": "KB-H",
    "resources": [
      "/lights/3"
    ],
    "type": "lights",
    "zigbee": true
  }
```

**Comment by ebaauw** [comment]
Did you enable adaptive lighting on this light?  Or did you try and set colour temperature from HomeKit?

**Comment by JanLp** [comment]
Yes ... and everything works as it should. I haven't gotten the error message since. I think the error came after a restart of homebridge-deconz. But I want to add that I got the error before version 2.20.01 and every time with IKEA lights

**Comment by JanLp** [comment]
By the way... thanks for the work on the homebridge-deconz plugin 🙂

**Comment by ebaauw** [comment]
Traditionally, Zigbee lights ignore commands to change brightness or colour (temperature) while off.  Traditionally, the deCONZ API checks whether a light is on, before sending a Zigbee command for such change, and issues the API error 201 when the light is off.

As I found out recently, the latest ZCL version includes an _Execute If Off_ flag in the (optional?) _Options_ attribute of both the _Level Control_ and _Color Control_ clusters.  Note that not all lights support these, but my _TRADFRI bulb E27 CWS 806lm_ does.  As of v2.20.x, the deCONZ API will no longer do the check nor issue API error 201, for lights that have the corresponding flag set.

I changed Homebridge deCONZ to update the colour temperature for adaptive lighting even when the light is off.  This went wrong initially, see #146, but should work now.  Hence my question whether you have adaptive lighting enabled on the light - the message should not be caused by adaptive lighting.  
If you simply try and change colour temperature from HomeKit while the light is off, this message is expected, unless the light supports and has enabled _Execute If Off_.  Note that this needs to be included explicitly in the DDF for the light, and proabably hasn't been done for the Trådfri lights.  And I don't expect the older Trådfri light to support this anyways.
