### ISSUE TITLE
warning: deCONZ not ready

### ISSUE THREAD

**Issue by Nastras** [ebaauw/homebridge-deconz#146]
I get this warning more often even though deCONZ is running and everything is working.

Do you have an explanation for this?

![IMG_4533](https://github.com/ebaauw/homebridge-deconz/assets/27686185/d2021f7d-01c3-493e-a286-4abae91d1199)

**Comment by ebaauw** [comment]
No, you'll have to check in the deCONZ log.

Homebridge deCONZ issues the warning when deCONZ reports `bridgeid` and/or `fwversion` as 0.  I understand this typically happens when the device has been disconnected (because of a deCONZ restart or watchdog leave/re-join or something similar).

**Comment by Nastras** [comment]
Uh-huh. I will check the deconz log if the error occurs again. The curious thing is that the error occurs only on one Pi out of three.
I will close here if it is a deCONZ error.
Thanks!

**Comment by Smooph86** [comment]
Hello, 

since I did a re-install and roll back from a backup of Homebridge and deCONZ, I have the same issue. Almost every hour (on the second!) I get the error "warning: deCONZ not ready" - but apart from that, everything works fine.

![Screenshot 2025-01-05 120856](https://github.com/user-attachments/assets/cbca7486-4188-4887-b623-2045a0f456cd)

If I monitor the events of the API in the Phoscon app, there's no event logged at that time or something suspicious - @Nastras, have you found something about that issue you've found?

Thanks!
