### ISSUE TITLE
Unreachable plug appears as On and unable to set wallSwitch

### ISSUE THREAD

**Issue by xorguy** [ebaauw/homebridge-deconz#156]
Hi.

I have a plug that as of now it is not plugged but appears as On. I have "No Response" setting enabled and tried to set wallSwitch for the specific device but it is not accepting the setting.

Log when tried to set wallSwitch:
`[deCONZ] Smart plug 7: warning: ui error: wallSwitch: invalid key`

Information of the device:
```
"manufacturer": "_TZ3000_g5xawfcq",
  "model": "TS0121",
  "name": "Smart plug 7",
  "resources": [
    "/lights/7",
    "/sensors/8",
    "/sensors/9"
  ],
  "settings": {
    "expose": true,
    "logLevel": 2,
    "serviceName": "Outlet"
  },
  "type": "lights",
  "zigbee": true
``` 

Is there any way to set the plug to appear as no response or at least off when not plugged in?

**Comment by ebaauw** [comment]
> I have a plug that as of now it is not plugged

Generally speaking, it's a bad idea to power down Zigbee routers.

> but appears as On

That's because deCONZ still reports it as on.  Unfortunately, you cannot change that while the device is powered down (unless you hack the database).

>  I have "No Response" setting enabled 

That's not yet implemented, see https://github.com/ebaauw/homebridge-deconz/wiki/Configuration.

> tried to set wallSwitch for the specific device but it is not accepting the setting.

Looks like I only implemented that for _Lightbulb_ services, and not for _Outlet_ and _Switch_ services.

**Comment by xorguy** [comment]
I know it is not the best idea to disconnect Zigbee routers, but it is due some changes I am performing at home.  Will try to connect in another location for the moment.

With wallSwitch maybe helps a bit when some plug is disconnected for some time. 

Thank you for all the work.

**Comment by ebaauw** [comment]
In v1.0.1.
