### ISSUE TITLE
Home+ no response 

### ISSUE THREAD

**Issue by Bentrama** [ebaauw/homebridge-deconz#17]
Hello,

i successfully added all the accessories to HomeKit and they work fine. 
But I have an issue on the home+ app, even if all the accessories works fine they are all in a “not responding” status in home+. Can you help me with that ?

**Comment by ebaauw** [comment]
And the accessories show OK in Home or another HomeKit app on the same device?  I don't think I've ever seen that before.  What happens if you refresh the screen in Home+ (drag the window down)?  And if you force-quit and restart Home+?

Usually not responding is caused by HomeKit on your device not receiving the mDNS announcements from the accessory (i.c. Homebridge).  Try switching WiFi off for a couple of seconds.

**Comment by Bentrama** [comment]
![7700E800-FDC2-4D04-8A19-1A0DC4B89826](https://user-images.githubusercontent.com/92755428/154359524-4e3ac204-3efe-4e62-b557-44a0cfd864cd.png)
![BCCD9B3B-126D-41C5-80B4-C481A2A3F029](https://user-images.githubusercontent.com/92755428/154359538-23fb4af3-0ce6-4131-b8a8-f8d6431100e5.jpeg)

Yes, they show ok in the native home app. And they work fine too.
Tried to refresh the home+ app but it didn’t change anything m, switching off wifi changed nothing too

**Comment by Bentrama** [comment]
Well I just switched off wifi for a second time then turned it back on and it is solved now
