### ISSUE TITLE
Philipps Bloom changes Saturation after a few seconds

### ISSUE THREAD

**Issue by naditz99** [ebaauw/homebridge-deconz#172]
I have an issue with my Philipps Bloom. When setting a specific color it changes the color (°) and saturation after a few seconds. It's not noticeable with the eye but you can see it in the log and it also deactivates my homekit scene.

[homebridge-deconz.json.gz](https://github.com/ebaauw/homebridge-deconz/files/12775151/homebridge-deconz.json.gz)
![ScreenshotProtocoll](https://github.com/ebaauw/homebridge-deconz/assets/122826296/2fc7ecad-fa99-428a-96f8-831452533786)

**Comment by ebaauw** [comment]
Next time, please attach the log file.  These screenshots are hardly readable.

At 6:38:13 PM, you set the colour from HomeKit to a _Hue_ 337° and _Saturation_ of 100%.  Homebridge deCONZ transforms the colour from the RGB colour space (used by computers) to the CIE 1931 colour space (used by TVs, and by Zigbee).  It sends `xy` values `[0.6256, 0.2648]` to the Bloom.  deCONZ initially echoes these values back, and then reports the values as reported by the Bloom: `[0.621, 0.2742]`.  Note the Bloom. like any RGB light, physically cannot re-create all colours, so it picks the closest matching colour is can display.  Homebridge deCONZ ignores this report (for now), since it's too soon after it has sent the command to change the colour, and sometimes a light might report a transitionary state.  At 6:38:17 PM, deCONZ polls the Bloom, that still reports `xy` of `[0.621, 0.2742]`.  Now Homebridge deCONZ transforms that back to RGB, resulting in a _Hue_ of 344° and a _Saturation_ of 85%.

As I mentioned in the other topic, HomeKit imho has a design flaw that it doesn't distinguish between target vs actual state of the light.  Consequenlty, this behaviour is to be expected: the HomeKit (target) values are updated with the actual values reported by the light (through deCONZ).

This doesn't "deactivate" the HomeKit scene, it just causes the HomeKit scene to display as no longer active.  You could try and modify the HomeKit scene to use  _Hue_ of 344° and a _Saturation_ of 85% (using a HomeKit app that let's you set numeric values rather than/in addition to selecting from a colour wheel).  But I'm not entirely sure that that will solve the issue of the scene showing as no longer active.  Between the light firmware (selecting the closest matching colour it can support) and the conversion from RGB to CIE1931 back to RGB slight variations in colour values are to be expected in my experience.  None of this is visible to the human eye, if the light actually displays different colours at all.

I see the Bloom is not exposed by deCONZ through a DDF, and deCONZ doesn't expose the colour gamut.  You should have seen a warning about using the default gamut at startup of Homebridge deCONZ.  The `modelid` of `929002376001` needs to be added (twice) to `light_zb3_C.json`.  I think Signify use slightly different `modelid` values for white vs black Blooms.  Also `colorcapabilities` hasn't been read (I'm pretty sure Signify won't expose this as `0`.

Off topic:
The IKEA TRAFDRI bulb E14 CWS 470lm are also missing the gamut.  By the looks of it, they might be very similar to the TRADFRI bulb E27 CWS 806lm in `tradfri_bulb_e27_cws_opal_806lm.json`, except that the E27 bulb doesn't have the firmware bug.  Both report the same firmware version, 1.0.021.  Does the E14 also use _Image Version_ 0x2802?  Did you actually test for the firmware bug (by sending a _Move to Level_ with a long _Transition Time_ (e.g. 3000 for 5 minutes) and then sending a _Move to Color Temperature_ or the other round)?

**Comment by naditz99** [comment]
I updated the file and now I don't get the gamut warning anymore. Also with an other app setting 344° and 85% solved the problem. My scene still does not stay active but I think that has to do with the issue #171 . I will test it some more, but I think it works now. Thank you!
