### ISSUE TITLE
"ui" Issues

### ISSUE THREAD

**Issue by bubffm** [ebaauw/homebridge-deconz#178]
Again issues with ui, I am afraid. After I tested that everything is working, I moved my homebridge / deconz setup from my old raspi3/raspBee1 to a new raspi4/raspBee2 setup. All is working fine. Zigbee devices and other homebridge stuff all showing up. But I want to stop that the new gateway (raspbee2) throwing so many log entries. Did a 'ping' against the gateway and received a "pong" back.

But trying to set loglevel via "ui" gets me this error. I checked for beautifications, but all looks fine to me
<img width="669" alt="Bildschirmfoto 2023-10-14 um 16 57 10" src="https://github.com/ebaauw/homebridge-deconz/assets/49747999/9f4c8783-1416-441f-9084-b5dbc7ec8425">

Any idea whats wrong? Could there be a rights issue?

**Comment by bubffm** [comment]
I do get a message in the Log that ui server is listening.

`ui server: listening on http://127.0.0.1:36841/`

**Comment by ebaauw** [comment]
`npm -g` installs symlinks to the command-line utilities in `/usr/bin` or `/usr/local/bin`, depending on how you installed NodeJS.  Local `npm` installs the symlinks in `.bin`.  Make sure the directory is included in $PATH, or the shell won’t be able to find the command.

**Comment by bubffm** [comment]
I installed homebridge from the standard setup procedure in Github.

Issuing "npm -g gives me:
pi@homebridge:~ $ npm -g
-bash: npm: command not found

Where do I need to check for that $PATH entry?  Sorry but this all sounds a but beyond me...

**Comment by ebaauw** [comment]
Sorry, closing this issue as this has nothing to do with Homebridge deCONZ.

> I installed homebridge from the standard setup procedure in Github. The homebridge-settings/plugins got restored on the new Pi via the UI-X interface from a backup

`npm` is the package manager that comes with NodeJS.   I don't know what the "standard setup procedure is" nor what kind of installation that would result in.  Apparently, it doesn't install NodeJS nor plugins in a way that they can be used from user `pi`.  You might try and issue the commands from the _Terminal_ in the Homebridge UI.  Otherwise, ask for help with Homebridge Config UI X, or Homebridge itself.

`$PATH` or `$HOMEBRIDGE_DIR` are Linux environment variables.  There are dozens of sites on the Internet explaining those.

**Comment by rhwood** [comment]
For anyone else struggling with `ui` not being in the path, you can use `sudo hb-shell` to get a terminal with `ui` in the path (and running as the correct user).
