### ISSUE TITLE
Exposed by draft ddf

### ISSUE THREAD

**Issue by marmitol** [ebaauw/homebridge-deconz#180]
Hi,

first of all, thank you very much for your efforts regarding the homebrige-hue and deconz theme, I appreciate your work!

I have recently installed and migrated to DECONZ. In the logs it shows me this message in yellow. Is it a mistake or do I have to take any corrective action?

Thank you.

<img width="1180" alt="image" src="https://github.com/ebaauw/homebridge-deconz/assets/61157812/1951c94e-0d3a-44b6-afcc-5a88a87672fa">

**Comment by ebaauw** [comment]
See the release notes: Homebridge deCONZ now checks whether deCONZ exposes each device by a proper DDF and issues a warning otherwise.  This might mean that deCONZ doesn't expose the full device capabilities, and therefore Homebridge deCONZ cannot use these.  To remedy, issue a device request in deCONZ to create a DDF for the device.

**Comment by marmitol** [comment]
Ok Thank you

**Comment by jan666** [comment]
> Is there a manual or reference to create DDF? Thank you.

https://github.com/dresden-elektronik/deconz-rest-plugin/wiki

**Comment by marmitol** [comment]
Thanks
