### ISSUE TITLE
Conbee 3

### ISSUE THREAD

**Issue by arkadicolson** [ebaauw/homebridge-deconz#186]
Hi

Is the new Conbee III gateway allready supported?

Thx
Arkadi

**Comment by ebaauw** [comment]
Haven’t received it yet, but I don’t expect any differences in the API, so most likely Homebridge deCONZ wouldn’t even notice.

**Comment by Patr-ick** [comment]
@ebaauw Just went through the migration according to https://phoscon.de/de/conbee3/upgrade
Only thing I had to do was storing the new API Key by pressing the "3rd party App - allow connection" button in Phoscon GUI.

Only messages I received at the beginning during the API connection are those:

`[10/11/2023, 16:57:32] [deCONZ] Phoscon-GW: unlock gateway to obtain API key - retrying in 15s
[10/11/2023, 16:57:32] [deCONZ] Phoscon-GW: warning: request 2: /: api error 101: link button not pressed
[10/11/2023, 16:57:47] [deCONZ] Phoscon-GW: warning: websocket communication error: Unexpected server response: 400
[10/11/2023, 16:57:47] [deCONZ] Phoscon-GW: websocket connection to ws://192.168.10.3:443 closed - retry in 15s
[10/11/2023, 16:57:47] [deCONZ] Phoscon-GW: Firmware Revision: set to "9.38.69" (from "0.0.0")
[10/11/2023, 16:57:47] [deCONZ] Phoscon-GW: warning: 203485A54C: potentially stale api key: {"create date":"2023-06-05T12:29:34","last use date":"2023-11-10T14:01:57","name":"homebridge-deconz#homebridge"}
[10/11/2023, 16:57:47] [deCONZ] Phoscon-GW: warning: 81C3C12649: potentially stale api key: {"create date":"2023-11-10T14:06:25","last use date":"2023-11-10T14:06:56","name":"homebridge-deconz#homebridge"}`

I assume it stored another API key next to the "old" one?

And let's see if we have to do the dynamic configuration again for the gateway and accessories, since already some messages in the log are re-appearing even after I've set the loglevel:0 weeks ago:

`[10/11/2023, 17:02:17] [deCONZ] Phoscon-GW Button: Programmable Switch Event: Single Press`

So far what I can contribute

**Comment by ebaauw** [comment]
I'm not sure what you have done.  If you do a proper backup and restore of deCONZ, the new coordinator device should be configured with the mac address of the old device, and the database, containing the API keys should be restored.  The `bridgeid` (taken after the coordinator device's mac address) should not have changed and Homebridge deCONZ would not have to obtain a new API key.

I fear with the new `bridgeid`, deCONZ has created a new Zigbee network, and your Zigbee devices need to be re-paired to that network.

Also, the new `bridgeid` will cause Homebridge deCONZ to see a new deCONZ instance, and, indeed, you would have to redo the dynamic configuration.

**Comment by Patr-ick** [comment]
As mentioned, I followed the migration steps from deCONZ which is literally just creating a backup, shutting down of the Pi, unplugging Conbee stick and inserting new one and fully booting the Pi again.

Then i just restored the backup in the Phoscon GUI and everything was set and done. 

According to the Homebridge log the plugin couldn't connect to the gateway, even after an homebridge reboot. So i pressed the link button again.

Thats it, lights where controllable again after that in Homebridge and Homekit. No loss of automations etc.

**Comment by ebaauw** [comment]
This is not the kind of use case I do regularly, but I might try this on a test network.

Anyways, I think we can conclude that Homebridge deCONZ works just as well with deCONZ using a ConBee III.  I'm just surprised that the `bridgeid` changed.

**Comment by arkadicolson** [comment]
@Patr-ick How did you get rid of messages like:
[11/23/2023, 10:45:36 AM] [deCONZ] Phoscon-GW Button: Programmable Switch Event: Single Press

It's not a big deal but rather annoying

**Comment by Patr-ick** [comment]
@arkadicolson This question was asked and answered multiple times. Please see the closed issues, for e.g. https://github.com/ebaauw/homebridge-deconz/issues/145 or https://github.com/ebaauw/homebridge-deconz/issues/30

**Comment by ebaauw** [comment]
Got the ConBee III and, indeed, Homebridge deCONZ doesn't see any difference from the ConBee and RaspBee I and II (other than the device type).

**Comment by Patr-ick** [comment]
@ebaauw Did you had to also grant a new API key and remove the old stale one?

**Comment by ebaauw** [comment]
The API key is part of the deCONZ REST API plugin.  It has nothing to do with the coordinator device.
