### ISSUE TITLE
Warnings - parameter, bri, is not modifiable

### ISSUE THREAD

**Issue by arkcolson** [ebaauw/homebridge-deconz#220]
Hi

Homebridge is printing a lot of warnings about Phoscon-GW

Phoscon-GW: warning: request 100946: /lights/21/state/bri: api error 201: parameter, bri, is not modifiable. Device is set to off.

Anybody an idea why and is there a way to supress them?

I'm running the latest version of homebridge with the latest version of the deconz plugin and latest firmware on my Conbee III

Thanks!

**Comment by ebaauw** [comment]
This is a waning about an error returned by deCONZ when you're trying to change the brightness of a light that's off, which the light doesn't support.  By design, there is no way to suppress warnings nor errors in Homebridge deCONZ.

You can prevent the error (and consequently the warning) by:
- Not changing the brightness from HomeKit, while the light is off.  Or rather: turn the light on before changing the brightness.  Not sure what HomeKit app you're using; most HomeKit apps do this automatically; and/or
- On lights with never firmware (and proper DDF support), in the deCONZ GUI set _Execute If Off_ on the _Options_ attribute of the _Level Control_ cluster, or set `config/bri/execute_if_off` through the deCONZ API, so that the light will support changing the brightness while it's off.
