### ISSUE TITLE
Additional light bulbs for ikea sensors and switches 

### ISSUE THREAD

**Issue by beatpaul** [ebaauw/homebridge-deconz#23]
Hi Erik!
I successfully switched to the deconz plugin!
All lights an sensors are working great! Thx for your work! Great Plugin!
One question: for certain switches and sensors i get an additional light 💡.  It is for ikea products mainly but not for aqara sensors e.g
Whats that for?
![E5E804B5-D369-4A8A-A4E0-9AB7265D7A5C](https://user-images.githubusercontent.com/33185643/155876894-add0501d-0ebf-4f21-a5f8-0727dbbffb81.jpeg)

Thx, Paul

**Comment by ebaauw** [comment]
It's probably the group bound to the switch.  Check the _Serial Number_ in Home, or the _Device Settings_ service in another HomeKit app.

**Comment by beatpaul** [comment]
You are right its a "LightGroup" !  only with the sensor in it i guess.
Is there a way i can change that ? the groups don't show up in Phoscon App.

**Comment by ebaauw** [comment]
Deselect _Expose_ on the _Device Setting_ of the group accessory.

**Comment by homefuzz-oz** [comment]
Hi @ebaauw,
just going through migrating my devices from homebridge-hue. Thanks for your work on the new platform!

I have the same "issue" with the light group being displayed. I set "Expose Groups" = Off in the Gateway setting, so I wonder why the groups get displayed anyways - as lights?

Interestingly, the switches (Tradfri Open/Close remotes) get recognised as such, but I can't blacklist them on gateway level, e.g. by an "Expose Switches" setting. Is there a reason why you only have Groups, Lights Schedule and Sensors on Gateway level? 

Last, the blacklisting of individual devices using Expose on the Device Setting doesnt seem to have any effect. For example, Phoscon has this virtual daylight sensor in Sensors. I have Expose Sensors -> Off and I have Expose -> Off on Device level, but I still see the sensor in Home.

**Comment by ebaauw** [comment]
The _Expose Groups_ and equivalent are more like “automatically expose new groups”.  Once expose, you need to clear _Expose_ in the _ Device Settings_ to stop exposing the group.

As for the daylight sensor, there’s two possible causes:
- Homebridge deCONZ is still exposing the sensor, even though it shows _Expose_ as off.  Make sure to refresh the screen in Eve, so it shows the current value instead of some stale value.  If it still shows _Off_, set _Expose_, wait a minute or so, and unset it.
- HomeKit still shows the old accessory, even though it has been removed.  As mentioned in the README, HomeKit really doesn’t like changes to the configuration, and it might take a while for these to be synced over iCloud to all your Apple devices.  There is also a limit on the size of the configuration, typically around 180 accessories, but I’m not entirely sure what counts towards this limit. Best check on different Apple devices, reboot the one that isn’t updated, or if that doesn’t help, sign out of iCloud and back into it.

**Comment by homefuzz-oz** [comment]
Ok, thank you! That explains some of the other behaviour I observed with the toggles as well. 
I have now moved everything over from Hue to deCONZ. All working happily and I find the IKEA blinds to be more responsive than with the previous plugin. Thank you again.
