### ISSUE TITLE
Question: How to get rid of "Ghost" devices

### ISSUE THREAD

**Issue by ursusHU** [ebaauw/homebridge-deconz#231]
Suddenly I have 2 non responding sensors appearing in Homekit. They of course appearing in the device list, but I couldn't find them anywhere else, definietly not in the phoscon app. I would like to get rid of them. How should I proceed?
`  "04CF8CDF3C75A4E6": {
    "expose": true,
    "manufacturer": "LUMI",
    "model": "lumi.plug.mmeu01",
    "name": "Consumption 12",
    "resources": [
      "/sensors/11",
      "/sensors/12"
    ],
    "type": "sensors",
    "zigbee": true
  },
  "04CF8CDF3C7771BC": {
    "expose": true,
    "manufacturer": "LUMI",
    "model": "lumi.plug.mmeu01",
    "name": "Consumption 10",
    "resources": [
      "/sensors/9",
      "/sensors/10"
    ],
    "type": "sensors",
    "zigbee": true
  },`

I have managed to make them disappear with:
`ui put /devices/04CF8CDF3C75A4E6 '{"expose": false}'`
but would be nice to know why they appeared.

**Comment by ebaauw** [comment]
They appear in HomeKit because deCONZ exposes the resources and you have `autoExpose` set.  You need to ask deCONZ why those resources appeared; you need to ask Phoscon why it doesn't show those resources.

Normally deCONZ exposes smart plugs using one `lights` resource (to control the on/off state) and two `sensors` resources (for consumption and power).  It looks like deCONZ only exposes the `sensors` resources for your ghost plugs.  My best guesses are:
- You deleted (unpaired) the plugs from deCONZ, but deCONZ didn't delete the `sensors` resources;
- The DDF for these plugs is broken.

Either way, this is an issue with deCONZ, not with Homebridge deCONZ.
