### ISSUE TITLE
Cannot connect to deconz 2.17.00 

### ISSUE THREAD

**Issue by miguelatv** [ebaauw/homebridge-deconz#51]
Cannot connect to deconz 2.17.00 running on same device. I get the following errors:
[deCONZ] warning: heartbeat 0, drift 265
[16/06/2022, 12:59:18] [deCONZ] warning: 127.0.0.1:4530: not a deCONZ gateway - retrying in 60s

I have tried with different host addresses including: the actual local IP address and localhost. I have confirmed I am using the correct port. (Installed deconz in homebridge raspberry pi using hb-config)

**Comment by ebaauw** [comment]
The error suggests that someone is listening on that port, but Homebridge deCONZ doesn’t recognise that as a deCONZ gateway.  What the output of `deconz -H 127.0.0.1:4530 -DD config`?

**Comment by ebaauw** [comment]
> It seems that the bridge id is zeros, may that be the issue?

Yes.  It should be the Zigbee MAC address of the coordinator.  Homebridge deCONZ stores a lot of date under the bridgeid and needs it to be valid.  Also note the deCONZ reports v2.16.1 instead of v2.17.0.
 
I’m not sure what’s causing this, nor how to fix it.  Does deCONZ even connect to the ConBee II (if that’s even the correct coordinator device)?  Does the GUI show the network map?  What does the deCONZ log say?

**Comment by kasik96** [comment]
Same problem :( Reinstall of HB and Plugin did not worked.

**Comment by kasik96** [comment]
Fixed for me. 

Update: I just reset my ConBee II and kept the original name for it, and then restarted HomeBridge. A voila, it works. So it must be some random nonsense that's happens in the universe sometimes. 

![image](https://user-images.githubusercontent.com/7235992/174497875-feb09199-c429-4a64-ab95-a0822e4d72b9.png)

**Comment by ebaauw** [comment]
It's an issue with deCONZ, so re-installing Homebridge deCONZ won't solve anything.  I've never experienced it myself, but have seen mention of it before.  It doesn't happen often, through.  No clue what causes it.

I'll change the error message to "not a RaspBee/ConBee mac address", since obviously is a deCONZ gateway alright.
