### ISSUE TITLE
What and where is "Gateway Settings service" and "Device Settings Service"?

### ISSUE THREAD

**Issue by MickL** [ebaauw/homebridge-deconz#55]
I got my gateway connected to Homebridge and it shows up in the iOS Home app. Anyway I dont see the sensors that I connected to Deconz in Homebridge. The readme states:

> After setting Expose Lights, Expose Sensors, or Expose Groups on the Gateway Settings service, Homebridge deCONZ will expose a [device accessory](https://github.com/ebaauw/homebridge-deconz/wiki/Device-Accessory) for each of the corresponding devices. When clearing the characteristic, the corresponding device accessories are removed from HomeKit.

But what and where is the "Gateway Settings service"? 

Also it says:

> Each device accessory has a Device Settings service, to configure the device. Clear Expose on that service, to blacklist the device, and remove the associated accessory from HomeKit.

But what and where is the "Device Settings service"?

**Comment by ebaauw** [comment]
These are custom HomeKit services.  Note that you need a decent HomeKit app to interact with them, as Apple’s Home app doesn’t support all of HomeKit.

**Comment by MickL** [comment]
I dont exactly understand. Do you mean "custom Homebridge plugins"?

I expected that the purpose of this plugin would be to make the devices that I have connected to deCONZ available in Homebridge (which makes them available in the Apple Home app). Isnt that the case?

**Comment by ebaauw** [comment]
HomeKit service = service proved by a HomeKit accessory.
Custom = defined by the accessory manufacturer, instead of by Apple.
This is all standard HomeKit terminology, as defined by Apple.

**Comment by keness521** [comment]
> I dont exactly understand what you mean by "custom HomeKit services". Do you mean "custom Homebridge plugins"?
> 
> I expected that the purpose of this plugin would be to make the devices that I have connected to deCONZ available in Homebridge (which makes them available in the Apple Home app). Isnt that the case?
> 
> From the readme:
> 
> > This [Homebridge](https://github.com/homebridge/homebridge) plugin exposes to Apple's [HomeKit](http://www.apple.com/ios/home/) ZigBee devices (lights, plugs, sensors, switches, ...) and virtual devices on a deCONZ gateway by dresden elektronik.
> 
> For me currently I have connected the following devices to deCONZ but none of them I find in Homebridge: 2 Aqara sensor, 1 Aqara switch, 1 Ikea remote control and 4 Ikea light bulbs. The only thing I see is the deCONZ gateway displayed as a switch.
> 
> The readme says:
> 
> > After setting Expose Lights, Expose Sensors, or Expose Groups on the Gateway Settings service, Homebridge deCONZ will expose a [device accessory](https://github.com/ebaauw/homebridge-deconz/wiki/Device-Accessory) for each of the corresponding devices.
> 
> But what is the "Gateway Settings service"?

At least for the time being, you have to use an unrelated, 3rd party app to configure most settings. For example, the Eve Home app. You don't actually have to have any Eve devices to use Eve, it's free. I find it a bit of a messy app, BUT, it does expose all properties of accessories which are added to HomeKit.

It's a complicated problem with no easy solution, and Erik is well aware of it and trying hard to come up with a less cumbersome method of configuring the settings of accessories. This plugin is working excellently, in a very short time, but it isn't technically a v1.0 yet, so be prepared for some beta-ness here and there. Erik is doing a LOT of hard work on this.

It is awkward, to bring in a whole additional 3rd party app just to configure settings, but Apple's Home app doesn't display all the properties that the others do. Also, in many cases you have to be logged into the same iCloud account that your HomeKit Home is part of, which if you have several homes can be a real challenge.

For many people, who use Eve (or similar) already, this isn't actually a big deal. But since it is definitely a round-about way to configure devices, I think he is working on a method of dealing with settings entirely contained within the Homebridge UI, or through a web interface which runs alongside the plugin. Either would be amazing, because you don't have to use a 3rd party program to configure settings. But either are also a TON of work!

A fair amount of angst comes from the fact that Apple's Home app doesn't expose all the properties the Eve app does, etc. (You'll have picked up on that from his reply to you when he said you'll need a "decent HomeKit app". haha) The challenge comes when trying to make software usable for a variety of users. Technical people may have no problem whatsoever with the Eve (or other) requirement. Whereas more general users (even advanced general users) might balk at needing to install a separate app just for configuring, if they might not have been using that app anyway.

Also, it can be said that many people gravitate towards Homebridge (and specifically Zigbee through Homebridge) specifically to REDUCE the number of hubs and apps needed, because of the ideal of have a single Zigbee controller (deCONZ).

But Erik definitely deserves a lot of kudos for all the effort he has put into this... It is a ton of work to create a UI from scratch for something as complicated as a whole ZigBee platform, with countless devices all with their own unique settings, etc.

Go ahead and read through the ReadMe again, he has all the information in there that you need. It might take a couple times, but it is all there. Hopefully with a little background on why things are the way they are right now, it will make a little more sense.

**Comment by MickL** [comment]
> HomeKit service = service proved by a HomeKit accessory.
> Custom = defined by the accessory manufacturer, instead of by Apple.
> This is all standard HomeKit terminology, as defined by Apple.

This might make sense for an iOS developer but most of the users of Homebridge (like me) are end users that only want to connect their devices and dont know about HomeKit terminology. IMO it would make sense to make the readme a bit more end user friendly. I still dont understand what is meant by "Gateway Settings service" and "Device Settings service", especially in context of Homebridge and homebridge-deconz
