### ISSUE TITLE
TRADFRI Switch seem don't working with latest version (v0.0.17)

### ISSUE THREAD

**Issue by adriengonz** [ebaauw/homebridge-deconz#56]
<img width="643" alt="Image PNG" src="https://user-images.githubusercontent.com/40824310/175057001-4a79a861-6d12-45c1-b701-a97ef8571293.png">

Hi, shortly after updated the plugin to version 0.0.17, when I press any button on the switch, this error appear on logs (in attachment).

So I had to switch back to the previous version (v0.0.16)

**Comment by adriengonz** [comment]
I have Homebridge installed on Raspberry Pi 4

**Comment by ebaauw** [comment]
Sorry for the late reply - It took me a while to find my Trådfri on/off switch.

I cannot reproduce this error.  It's caused because Homebridge deCONZ receives a `buttonevent` notiication from the on/off switch, but somehow, it's seems to have lost the link between the accessory and the resource.  No clue what caused this: maybe an upgrade of deCONZ (now exposing the switch through DDF, maybe); maybe an upgrade of Homebridge deCONZ.

Could you try and un-expose the on/off switch, wait a while and then re-expose it?  I think/hope that will correctly link the resource to the accessory.

If that doesn't help, could you please attach the dump file, set _Log Level_ for the switch to 2, and capture the Homebridge log file.

**Comment by adriengonz** [comment]
Hi, I updated Homebridge-deCONZ at his last version (0.0.21) and now it's working fine

Thanks a lot !

**Comment by reinisb** [comment]
@adriengonz Could you please share the config you use in Homebridge for the Trådfri on/off switch? I'm asking since I'm about to install deCONZ and Homebridge-deCONZ to use my Trådfri on/off switch via Conbee II. Thank you!

**Comment by adriengonz** [comment]
Hi @reinisb, I didn't saw your message before.

That's my config on Homebridge :

`        {
            "name": "deCONZ",
            "hosts": [
                "****"
            ],
            "_bridge": {
                "username": "****",
                "port": ****
            },
            "platform": "deCONZ"
        },`
        
 I added my Conbee local IP and the deCONZ plugin is in charge of the rest
