### ISSUE TITLE
Show device name when the service is disabled

### ISSUE THREAD

**Issue by oleksiikutuzov** [ebaauw/homebridge-deconz#60]
Currently, when device service is off, it has the default 'Phoscon-GW Deconz' name. The real device name appears only when you turn it on. So you can't really turn on what you need unless you know under which number it is saved.

![IMG_0765 copy](https://user-images.githubusercontent.com/8535871/181115987-86b16a1d-8900-4ac9-91d0-609ead46af5a.PNG) ![IMG_0766 copy](https://user-images.githubusercontent.com/8535871/181115974-6d91e137-1ff4-4cac-ba8d-3e89466cc22b.PNG)

**Comment by ebaauw** [comment]
Weird, I cannot reproduce this.  What happens if you force-quit and restart Eve?
What happens if you de-select _Expose Sensors_, wait a bit for the device services to disappear, and then select it again?

**Comment by oleksiikutuzov** [comment]
> What happens if you force-quit and restart Eve?

Nothing changes, this doesn't seem to be Eve's issue. Same behavior in Controller for HomeKit app.

> What happens if you de-select _Expose Sensors_, wait a bit for the device services to disappear, and then select it again?

They re-appear in the same state – the ones enabled with their names and ones disabled with the default gateway name.

Should I try reinstalling the plugin?

**Comment by ebaauw** [comment]
Re-installing the plugin won't make a difference, I think.  You might try un-exposing the deCONZ gateway (which will also un-expose all connected devices), waiting for HomeKit to settle down, and re-expose the gateway.

I have no clue what's causing this.  I'm trying to set the configuration from the Homebridge UI, instead of from HomeKit itself.  If that succeeds, I'll remove the _Device Settings_ services, and this problem becomes obsolete.

**Comment by oleksiikutuzov** [comment]
Yeah, okay, then it's not so important if you are going to remove this feature anyway
