### ISSUE TITLE
SyntaxError: lastUpdated: duplicate key

### ISSUE THREAD

**Issue by torandreroland** [ebaauw/homebridge-deconz#66]
I haven a [Develco Smart Plug Mini](https://www.develcoproducts.com/products/smart-plugs/smart-plug-mini/) that was working flawlessly with Homebridge Deconz until the recent updates (before 0.0.18 / 0.0.19). Since then I get syntax error about last updated being duplicate. If I remove the outlet using the "Remove Single Cached Accessory"-functionality in Config UI X, the error goes away, but after some time it starts to appear again.

While the error is present, the outlet is unresponsive in HomeKit. I have two outlets of the same type. The other outlet works as intended, even if the other is having the error / is unresponsive.

If I try to toggle the outlet within the Deconz VNC GUI, it responds as expected, even when the error in Homebridge is present.

Here is the log:

[8/14/2022, 10:24:18 AM] [deCONZ] Outlet: Develco Products A/S SPLZB-131 v3.c.4 (3 resources)
[8/14/2022, 10:24:18 AM] [deCONZ] Outlet: warning: On: 3 listeners
[8/14/2022, 10:24:18 AM] [deCONZ] Ekraveien 18: error: SyntaxError: lastUpdated: duplicate key
    at Power.addCharacteristicDelegate (/homebridge/node_modules/homebridge-deconz/node_modules/homebridge-lib/lib/ServiceDelegate/index.js:240:13)
    at Power.addCharacteristicDelegates (/homebridge/node_modules/homebridge-deconz/lib/DeconzService/SensorsResource.js:23:12)
    at new Power (/homebridge/node_modules/homebridge-deconz/lib/DeconzService/Power.js:72:11)
    at Light.createService (/homebridge/node_modules/homebridge-deconz/lib/DeconzAccessory/index.js:184:17)
    at new Light (/homebridge/node_modules/homebridge-deconz/lib/DeconzAccessory/Light.js:46:14)
    at Gateway.addAccessory (/homebridge/node_modules/homebridge-deconz/lib/DeconzAccessory/Gateway.js:540:25)
    at Gateway.analyseFullState (/homebridge/node_modules/homebridge-deconz/lib/DeconzAccessory/Gateway.js:910:20)
    at Gateway.poll (/homebridge/node_modules/homebridge-deconz/lib/DeconzAccessory/Gateway.js:733:18)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Gateway.heartbeat (/homebridge/node_modules/homebridge-deconz/lib/DeconzAccessory/Gateway.js:276:9)

**Comment by ebaauw** [comment]
> [8/14/2022, 10:24:18 AM] [deCONZ] Outlet: warning: On: 3 listeners

That's not good.  There are multiple delegates for the same accessory.

> If I remove the outlet using the "Remove Single Cached Accessory"-functionality in Config UI X,

Best not use that, but un-expose the device (using the _Device Settings_ service in Eve), wait for HomeKit to delete the corresponding accessory, and re-expose it.  If that doesn't solve the issue, please attach the debug dump file.

**Comment by torandreroland** [comment]
Thanks for quick response. I'll try that when the error resurfaces and let you know / attach debug dump file.

**Comment by torandreroland** [comment]
I ended up looking into the code. I think there at least is a problem in Power Service constructor [here](https://github.com/ebaauw/homebridge-deconz/blob/8ce0f739c2d1f38e7cb99c258bf73d6538e94c93/lib/DeconzService/Power.js#L70:L72).

In [Power.addResource](https://github.com/ebaauw/homebridge-deconz/blob/8ce0f739c2d1f38e7cb99c258bf73d6538e94c93/lib/DeconzService/Power.js#L42:L49) lastUpdated-characterstic is added first.

Then in [super.addCharacteristicDelegates](https://github.com/ebaauw/homebridge-deconz/blob/1a27db34ddfb8d00705637a099323bec1abf8a5a/lib/DeconzService/SensorsResource.js#L22:L28) lastUpdated-characterstic is added again, leading to the duplicate-error. Should super.addCharacteristicDelegates have been called with { noLastUpdated: true } as [being done by the Switch-service](https://github.com/ebaauw/homebridge-deconz/blob/bf997469c3d1d84bdff77e3768b44b0df3788bf8/lib/DeconzService/Switch.js#L24)?

**Comment by ebaauw** [comment]
The code is complex: sometimes the `lights` resource and the ZHAConsumption and ZHAPower `sensors` resources need to be combined in a single _Outlet_ service; other times there’s no `lights` resource, and the ZHAConsumption `sensors` resource needs a new service.  I think something in the internal resource administration has changed, and the new version of Homebridge deCONZ incorrectly handles the setup from the previous version.  Un-exposing/re-exposing the accessory should fix that; just deleting the plug from `cachedAccessories` wouldn’t, as the resource administration is stored under the gateway.

**Comment by torandreroland** [comment]
The debug dump file is [available here](https://1drv.ms/u/s!Am3DKtLr0F3Kg8IOVj7FXXOk_3-QUg?e=MHmS3X).

The smart plug that has the error is made up of resources /Lights/15, /Sensors/39 and /Sensors/40, while the equivalent smart plug that is working correctly is made up of resources /Lights/3, /Sensors/35 and /Sensors/36.

Some more info:
- The smart plug in question is added correctly the first time in Deconz (either by removing the single accessory from Homebridge-cache or setting it up as a new a new accessory in Deconz), but the error is showing immediately on the first restart.
-  Un-exposing/re-exposing the accessory in Homebridge Deconz doesn't work. The whole device is unresponsive, leading to inability to unexposing it also.
- Removing the device in Deconz and adding it again with new resources (i.e. new /Lights/X and /Sensors/Y) doesn't help. The device fails once again on the first restart.

Again, I have no idea why this is only happening with one of the smart plugs and why it suddenly started to be an issue after working flawlessly for months. As you I suspect some changes within Deconz itself, but the two devices looks identical in the Deconz REST API (as evident by the debug dump file.

But as I pointed out in my previous comment, calling super.addCharacteristicDelegates with { noLastUpdated: true } at least solves the issue for my part. I'm not sure if it has any negative consequences for other type of devices as you mentioned.

**Comment by ebaauw** [comment]
The order of the `sensors` resources differs.  The working plug has ZHAConsumption (35) before ZHAPower (36), whereas the erroneous plug has ZHAPower (39) before ZHAConsumption (40).  Also the `lights` resource for this device doesn't contain `state.bri`, so Homebridge deCONZ exposes it as an _Outlet_ instead of _Lightbulb_.

I intended the device to be exposed as a single _Outlet_ service, with the characteristics for the ZHAConsumption and ZHAPower resources added to the _Outlet_ service.  However, due to a bug in `DeconzAccessory.addService()`, it doesn't check for an _Outlet_ service, causing a new _Resource_ service to be created for the first `sensors` resource.  As `DeconzService.Power.addResource()` checks whether `lastupdated` has already been added (presumably by `DeconzService.Consumption`, the duplicate key only appears when the ZHAPower resource appears first.

So what does the device look like in Eve?  I assume it shows correctly the two services (one _Outlet_ and one _Resource_) as one, because of the _History_ service.  But does it show the wattage in the _Room_ view?  Do you have Home+ or other HomeKit apps?  How do these show the accessory?

So there's a couple of bugs, whose combination causes the error:
- `DeconzAccessory.addService()` should check for _Outlet_ in addtion to _LightBulb_;
- `DeconzService.Consumption.addResource()` should also add the _Last Updated_ characteristic (in case of a device with a `lights` and ZHAConsumption resource, but without a ZHAPower resource).
- Both `DeconzService.Consumption` and `DeconzService.Power` constructors should indeed call `super.addCharacteristicDelegates()` with `{ noLastUpdated: true }` (for devices without a `lights` resource, but with ZHAConsumption and/or ZHAPower).
- For devices with a `lights` resource, similar logic is missing for exposing `config.on` as _Enabled_ and _Status Active_.

**Comment by ebaauw** [comment]
In v0.0.21.

**Comment by torandreroland** [comment]
Hi! Thanks for the fix. It’s working now.

Viewing the device in HomeSpy (which I believe shows pretty much raw HomeKit-information) before the update, showed the following services for these devices:
- Accessory Information Service
- Outlet
- Power (Custom service)
- History (Custom service)
- Settings (Custom service)

After the update, the Power-service is gone and the characteristics which was part of the Power-service has been moved to the Outlet-service (as I gather is the intention based on your comment).

Closing this issue.
