### ISSUE TITLE
The internal switch may interfere with physical button.

### ISSUE THREAD

**Issue by ursusHU** [ebaauw/homebridge-deconz#69]
After I installed homebridge-deconz, and setup my ikea buttons, I realized that the one of the button presses created automatically in the plugin somehow interferes with a physical button press automation. One of my buttons (ikea tradfri on/off) is sending home the vacuum, and yesterday evening I experienced this 2 times and never before (then I gave up and sent the vacuum back) that during the vacuuming the unit behaved like that button was pressed. And it looked like in the logs that it could be in the same time when the button press was done in homebridge deconz.

ps.: I have reinstalled hb-hue again, and suprisingly in iOS 15.6 the non-supported Phoscon tile can be removed again from the favourites - if I understood correctly why you changed in the new plugin the type.
![kép](https://user-images.githubusercontent.com/61931127/185590895-bcf3a8ae-6b4b-43d6-bc66-d2123df40eda.png)

**Comment by ebaauw** [comment]
> suprisingly in iOS 15.6 the non-supported Phoscon tile can be removed again from the favourites 

Indeed, this is good news.  I added a dummy _Stateless Programmable Switch_ service to accessories that would otherwise show as a _Not Supported_ tile in Home.  Guess I can remove these now (or comment them out, you never know what Apple might do in a next iOS version...).

>  I realized that the one of the button presses created automatically in the plugin somehow interferes with a physical button press automation.

I really need to see a debug log (including the communication with deCONZ) to assess this.  I'm not saying it's impossible, but it seems highly unlikely to me.  More likely in my experience: the switch is sending irregular messages to deCONZ, typically in low-battery conditions, or your home hub it acting up (see e.g. https://github.com/ebaauw/homebridge-hue/issues/1107).
