### ISSUE TITLE
Superfluous configured name characteristic for settings service

### ISSUE THREAD

**Issue by torandreroland** [ebaauw/homebridge-deconz#84]
I feel the configured name characteristic for the settings service is at best superfluous and mostly confusing. My understanding is that this should mirror the name of the resource, but the characteristic of the settings service doesn't have a resource counterpart.

**Comment by torandreroland** [comment]
I have a thermostat that is exposed as one sensor resource in the deconz api. This is represented as an accessory in HomeKit with three services:
- Accessory Information (HomeKit native)
- Thermostat (HomeKit native)
- Settings (Custom)

Both the thermostat and settings services have a configured name charactestic, but only the characterstic of the thermostat service is actually linked to the name of the sensor resource in the deconz api.

Below is JSON-representation of the sensor from the API:

{
    "config": {
        "heatsetpoint": 2200,
        "locked": false,
        "mode": "heat",
        "offset": 0,
        "on": true,
        "reachable": true
    },
    "etag": "1c75a7a1c86185f2b6a9a09a4d107d7c",
    "lastannounced": null,
    "lastseen": "2022-11-21T17:32Z",
    "manufacturername": "ELKO",
    "modelid": "Super TR",
    "name": "Downstairs Bathroom Floor Heatin",
    "state": {
        "lastupdated": "2022-11-21T17:32:35.076",
        "on": false,
        "temperature": 2220
    },
    "type": "ZHAThermostat",
    "uniqueid": "00:0d:6f:00:0f:55:6f:a3-01-0201"
}

**Comment by ebaauw** [comment]
They're all linked.  When you change the `name` on the REST resource in deCONZ, Homebridge deCONZ updates the names of all three services.  When you change the name of the (primary) Thermostat service, Homebridge deCONZ updates the `name` of the resource, and then updates the names of the _Accessory Information_ and _Device Settings_ services (because the `name` on the resource has changed).  When you change the name of the _Device Settings_ service, Homebridge deCONZ does nothing.  I don't know of any HomeKit app that allows you to change the name of the _Accessory Information_ service.

**Comment by ebaauw** [comment]
> This is obviously nitpicking.

OK, so we can close this issue?

> However I still hold that Device Settings service shouldn't have a configured name characteristic. Potentially one can argue that it's the only service which should have a configured name characteristic, omitting it from the other services to bypass the cardinality aspects described in the previous paragraph.

I'm planning to ditch the _Device Settings_ service, once I'll have figured out how to do dynamic settings from the Homebridge UI.

Each service should have _Configured Name_.  Since iOS 16, HomeKit screws up the initialisation of service names, and uses the accessory name for each service.  This sucks for accessories with mulitple services of the same type, as you can no longer distinguish these in Home or another HomeKit app.  By adding _Configured Name_, HomeKit on iOS 16 links the service name to its value, making it settable from the accessory (i.c. Homebridge plugin).

Whether or not you want to update _Configured Name_ when the resource name changes, or whether or not you want to update resource name when user changes the service name (which changes _Configured Name_), is a different question, see #83.

> But my opening comment here wasn't spot on as you point out, since one device may be:
> - represented with multiple resources in the REST API which can be combined into one HomeKit-service
> - represented with one resource in the API which may be split into multiple HomeKit-services (your example of battery-services)

In principle, a Zigbee device is exposed as a single HomeKit accessory, with a HomeKit service per REST API resource.  As you indicate, there are some exceptions to this principle:
- Wireless switches have _Label_ service and a _Stateless Programmable Switch_ service per button, independent of how many ZHASwitch and/or ZHARelativeRotary resources they use;
- ZHAConsumption and ZHAPower resources are currently exposed on the primary _Lightbulb_, _Outlet_, or _Switch_ service, to accommodate Eve history.  That might change, however; I got myself an Eve Energy Strip on Black Friday, and it exposes three _Outlet_ services and a custom service for the consumption and power.  I need to test if I Eve accepts the same custom service on an accessory with a single _Outlet_, _Switch,_ or _Lightbulb_ service;
- As you mentioned, `config/battery` is currently exposed as a separate service.  In deCONZ APIv2, battery will be exposed as a separate subdevice (cf. the ZHABattery for window covering devices, that are exposed as `lights` resource);
- ZHAAirPurifier is exposed as two services, _Air Purifier_ and _Filter Maintenance_, in line with HomeKit standard services.

In Homebridge Hue, you can use resourcelinks to combine multiple CLIP resources into a single MultiClip accessory or to split a device into multiple accessories (to accommodate wired in-wall switches with wires to ceiling points in different rooms).  I want to offer similar features to Homebridge deCONZ as well (once I'll have sorted out the settings).

**Comment by torandreroland** [comment]
Thank you for the extensive answer. Yes, you can close this issue.
