### ISSUE TITLE
Switch names resetting to 'Button 1'

### ISSUE THREAD

**Issue by domdtyler** [ebaauw/homebridge-deconz#87]
I have a number of IKEA TRADFRI button switches, which I am connecting to HomeKit via a Conbee II and homebridge-deconz running on an RPi 4. The buttons expose into HomeKit but their names continually reset to 'Button 1'. This makes it somewhat difficult to distinguish between them, requiring me to open the Advanced Features in Home+ (which does show the correct name as pulled through from Phoscon). I have tried changing the name in Home+, which sticks for a few minutes before the name resets to 'Button 1'.

I believe this may be a bug, but if I'm missing a setting somewhere, please do let me know!

**Comment by ebaauw** [comment]
I think that's a feature of Home+.  I shows the label, like Apple's Home app, instead of the service name.  I do see the changed service name in Eve, even after Home+ has reverted to the label.

As of iOS 16, service names are initialised from the accessory name, instead of the service name, as exposed by the accessory (i.c. the Homebridge plugin).  I see that I don't yet expose _Configured Name_ on the _Stateless Programmable Switch_ service - will add that to the next release.

**Comment by domdtyler** [comment]
Thanks for the clarification! I think between this and #88, I need to have a chat with the Home+ developer! Thank you for all your excellent work on homebridge-deconz! It's fantastic and I much prefer the HomeKit-side control we get too!
